### ISSUE TITLE
Some phone numbers are not working in India

### ISSUE THREAD

**Issue by dev-vinoth** [iziz/libPhoneNumber-iOS#186]
In India some of the new mobile numbers or not working. Like mobile number start with 86677, 86673, etc.,

I am using latest pod -> (0.9.6)

**Comment by iziz** [comment]
Sorry for late, was very very very busy :(
Would you try with 0.9.7 ?

**Comment by dev-vinoth** [comment]
@iziz When I tried with 0.9.7 getting two compile errors

1. Include of non-modular header inside framework module 'libPhoneNumber_iOS.NBGeneratedPhoneNumberMetaData'

2. Could not build Objective-C module 'libPhoneNumber_iOS'

**Comment by iziz** [comment]
Are you using with swift ?

**Comment by RndmTsk** [comment]
I'm still seeing the issue:

Include of non-modular header inside framework module 'libPhoneNumber_iOS.NBGeneratedPhoneNumberMetaData' (using 0.9.8)

**Comment by iziz** [comment]
Revert metadata to legacy way (0.9.10)

**Comment by RndmTsk** [comment]
Thanks, it works again for me!

**Comment by dev-vinoth** [comment]
@iziz No (0.9.10) also not working for both mobile numbers mentioned(866776407* & 866734535*)

**Comment by iziz** [comment]
@dev-vinoth Ref. below~
You can check phone number validation using below link. https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Please report, if the above results are different from this iOS library. Otherwise, please create issue to following link below to request additional telephone numbers formatting rule. https://github.com/googlei18n/libphonenumber/issues

Metadata in this library was generated from that. so, you should change it first. :)

**Comment by dev-vinoth** [comment]
This link(https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) provide the number is FIXED_LINE_OR_MOBILE. 
iOS Library also done the same job. thank you @iziz now I am closing the issue.
