### ISSUE TITLE
Swift problem

### ISSUE THREAD

**Issue by cyril94440** [iziz/libPhoneNumber-iOS#21]
Hello, 

I use the following code 

 var errorPointer:NSError?
 var number:NBPhoneNumber = phoneUtil.parse(sender.text, defaultRegion: region, error: &errorPointer)

and I get the following error : 
fatal error: unexpectedly found nil while unwrapping an Optional value

Do you know where it comes from ?

Thx

**Comment by rishimukherjee** [comment]
I am getting the same error! Not sure what the problem is:

    func isPhone(text: String) -> Bool {
        var errorPointer: NSError?
        // Error comes in the line below.
        var number:NBPhoneNumber = phoneUtil.parse(text, defaultRegion: "KR", error: &errorPointer)

        if errorPointer == nil {
            return phoneUtil.isValidNumber(number)
        }
        return false
    }

**Comment by yarneo** [comment]
actually the problem is with the example. In your case it works so there is no error and the function doesn't return a nil.

However, when there is an error, the function return a nil and you can't put a nil in a non-optional value such as NBPhoneNumber.

Therefore the correct way to do the example is:

var phoneUtil = NBPhoneNumberUtil.sharedInstance()
    var errorPointer:NSError?
    var number:NBPhoneNumber? = phoneUtil.parse("01041241282", defaultRegion:"KR", error:&errorPointer)

**Comment by iziz** [comment]
Thanks~
