### ISSUE TITLE
Deprecation of singleton

### ISSUE THREAD

**Issue by futuretap** [iziz/libPhoneNumber-iOS#47]
I'm wondering why you deprecated the sharedInstance… methods. Didn't it make sense to use the shared instance for caching purposes?
Should I really create a new instance for each phone number check?

Would be great if you could elaborate on the reasoning and how we should change our code when using the lib.

**Comment by iziz** [comment]
Yep, You don't worry about that.
Before 0.8.x, "NBPhoneNumberUtil" has Phone number meta data.
But, now (0.8.x) it was moved to NBMetadataCoreMapper.

**Comment by futuretap** [comment]
Thanks, so we'll switch to allocating the object freshly.

**Comment by iziz** [comment]
OK, But if you want to use "sharedInstance" for your convenience, just tell me.
I will remove deprecated mark.

**Comment by futuretap** [comment]
No, not a big deal to change it. Actually it saves me from doing the locking on my side. I assume the lib can be called from arbitrary threads?

**Comment by iziz** [comment]
Yep, I assumed it. (and welcome your idea for get rid out of inefficient logic.)

**Comment by juhovh** [comment]
Actually I think I would like to have the sharedInstance not deprecated.

I'm working with ReactiveCocoa and libPhoneNumber, and I do not want to refer to self from inside my blocks to make the code more functional. In order to do that I would need a singleton to NBPhoneNumberUtil and it feels silly to duplicate exactly what is already present in [NBPhoneNumberUtil sharedInstance].

I don't really care about the other singleton methods than the basic one, constantly allocating multiple NBPhoneNumberUtil instances on every keypress is just not a good idea IMHO, the singleton should perform better.

**Comment by iziz** [comment]
I see, I will remove deprecation mark. 
It is not important issue for singleton or creating instance. and "provide convenience" is more important :)

Anyway, I think it is not main problem "thread safety" in current libphonenumber-ios, but please create the issue if you find some thread problem.

thanks for your feedback.

**Comment by juhovh** [comment]
Ok, thank you!
