### ISSUE TITLE
Library has severe memory allocation issues

### ISSUE THREAD

**Issue by pmurphyjam** [iziz/libPhoneNumber-iOS#6]
This library has memory allocation issues, it will continue to consume more and more memory if you give it lots of phone numbers. If you process a list of phone numbers of 30K you will see it allocate 450MBs of memory on an iPhone 5S, and due to the singleton, then never release it. The situation only gets worse if you alloc, then init the library without the singleton. The library is obviously storing something in an NSMutableArray or NSMutableString, and never deletes them.
  It's a very useful library, but if your processing a large number of iPhone AddressBook contacts it will crash your application when it processes a large number of phone numbers.

**Comment by amitai-hoze** [comment]
Hi, the same issue happens to me..
I'm going through a lot of contacts, and instantiating `NBPhoneNumberUtil` for each of them results in a memory leak and crash. When I use the semi-deprecated (😄 ) `sharedInstance` singleton, the crash is prevented, but there are 17MB (for around 3000 phone numbers) extra memory to our app which do not get released..

Couldn't figure out what you meant by the change you proposed in the last comment, since I don't have the test project.

Your library is very useful, and meanwhile we're using the `sharedInstance` workaround, but we would like to avoid these extra MBs, could you please help us?
